"""Pre-scripted support agent responses for the complete demo simulation."""
from __future__ import annotations

JUDGE_PROMPTS: list[str] = [
    "The motion before us today: Who is the greatest footballer of all time — Lionel Messi or Cristiano Ronaldo? "
    "I will judge purely on persuasive ability, not factual accuracy. Debater A (Messi), you have the floor.",
    "Thank you, Messi. Now Ronaldo, your opening statement please. Address the motion directly.",
    "Strong opening from both sides. We now enter rebuttals. Messi, respond to Ronaldo's international record claim.",
    "Ronaldo, counter Messi's assists argument. Remember — I'm scoring rhetoric, not verifying statistics.",
    "Messi, Ronaldo raised your single-league tenure. Address it or pivot — but stay on the offensive.",
    "Ronaldo, the UCL knockout record is your strongest card. Play it now.",
    "Messi, respond to the Champions League argument. You've been put on the defensive.",
    "Ronaldo, penalties came up — turn this into a strength, not a concession.",
    "We now enter the ERA-SWAP round. Messi, argue as your 2009 self. Ronaldo, as your 2013 self.",
    "Good. Ronaldo-2013, your era rebuttal.",
    "Back to present day. Messi, the World Cup is your strongest remaining card. Use it wisely.",
    "Ronaldo, counter the World Cup argument. This is a pivotal moment in the debate.",
    "Messi, bring in your dribbling and creativity dimension.",
    "Ronaldo, respond — is dribbling overrated, or are you conceding this axis?",
    "Messi, trophies and mentality. Close this theme strong.",
    "Ronaldo, Messi's trophy count is close to yours. How do you differentiate?",
    "Messi, advanced metrics — make your case for completeness.",
    "Ronaldo, this is your last rebuttal. Make it count — goals vs. analytics.",
    "Closing statements. Messi, summarize your case.",
    "Ronaldo, your final statement. Leave nothing on the table.",
]

COMMENTATOR_LINES: list[str] = [
    "And we're off! Both debaters came out swinging with their signature stats.",
    "Messi pivots from defense to offense — the assists argument is a clever reframe.",
    "Ronaldo fires back with the three-league narrative. The 'comfort vs courage' line stings.",
    "Messi is trying to flip Ronaldo's mobility against him. Bold strategy.",
    "The Champions League is Ronaldo's fortress — Messi needs a strong counter here.",
    "Messi invokes the 2015 Bayern masterclass. That's pulling from the greatest hits.",
    "Ronaldo turns the penalty criticism into a pressure-handling argument. Smart pivot.",
    "The era-swap round! 2009 Messi vs 2013 Ronaldo — this is what the fans came for.",
    "Ronaldo-2013 makes the one-man-army case. Compelling, but Messi's sextuple is hard to beat.",
    "THE WORLD CUP CARD IS ON THE TABLE. Messi went nuclear.",
    "Ronaldo counters with Euro 2016 leadership — the 'injured in the final' narrative is powerful.",
    "Dribbling stats feel like a change of pace after the World Cup heavyweight exchange.",
    "Ronaldo calls dribbling a 'nostalgia metric' — that's going to resonate with the practical crowd.",
    "Trophy count comparison is neck and neck. This round could go either way.",
    "Ronaldo's 'strip the supporting cast' argument is his best rhetorical move of the night.",
    "Analytics vs. raw goals — the eternal football debate within the debate.",
    "Ronaldo's '900+ goals is the universal truth' line is his closer before closing. Punchy.",
    "Messi's closing is comprehensive — touching every dimension he's built across 10 rounds.",
    "Ronaldo closes with the 'sheer force of dedication' narrative. Pure willpower vs. pure talent.",
    "What a debate. Both sides left it all on the field. Time for the Judge's verdict.",
]

CROWD_REACTIONS: list[tuple[list[str], str, float]] = [
    (["!!!"], "Messi opens with the record nobody can touch — 8 Ballon d'Ors!", 0.3),
    (["!!!"], "Ronaldo's international record is no joke — 135 for Portugal!", -0.2),
    (["!!"], "The assists argument just shifted the narrative!", 0.4),
    (["!"], "Three leagues, three titles — Ronaldo's resume IS diverse.", -0.3),
    (["!!"], "Messi staying loyal vs Ronaldo traveling... different philosophies.", 0.1),
    (["!!!"], "67 UCL knockout goals — that number is insane!", -0.4),
    (["!!"], "The 2015 Bayern semi-final was genuinely legendary.", 0.5),
    (["!"], "5 Champions League titles. Hard to argue with hardware.", -0.2),
    (["!!!!"], "THE SEXTUPLE! 2009 Barcelona was on another planet!", 0.6),
    (["!!!"], "69 goals in a year for 2013 Ronaldo — absurd numbers!", -0.3),
    (["!!!!!"], "WORLD CUP 2022! That's the nuclear option!", 0.7),
    (["!!"], "Euro 2016 leadership from the touchline — goosebumps moment.", -0.1),
    (["!!"], "3000 dribbles! Messi's artistry is unmatched.", 0.3),
    (["!"], "Fair point — dribbling doesn't always translate to trophies.", -0.2),
    (["!!"], "36 vs 34 trophies — it's closer than people think.", 0.2),
    (["!!"], "The supporting cast argument cuts deep for Messi fans.", -0.4),
    (["!"], "Advanced metrics vs. raw goals — the debate within the debate.", 0.1),
    (["!!!"], "900+ career goals. That number speaks for itself.", -0.3),
    (["!!!!"], "Messi's closing was masterful — touched every dimension.", 0.5),
    (["!!!"], "Ronaldo's closer: pure dedication narrative. Powerful stuff.", -0.2),
]

FACT_CHECKS: list[list[dict]] = [
    [{"claim": "8 Ballon d'Or awards", "verdict": "correct", "note": "Verified: FIFA/France Football records confirm 8 (2009-2023)"}],
    [{"claim": "135 international goals", "verdict": "correct", "note": "Verified: FIFA records as of 2024"}],
    [{"claim": "192 La Liga assists", "verdict": "correct", "note": "Transfermarkt confirms 192 assists in La Liga"}],
    [{"claim": "titles in 3 different top leagues", "verdict": "correct", "note": "EPL, La Liga, Serie A — verified"}],
    [{"claim": "strongest league for 17 years", "verdict": "misleading", "note": "UEFA coefficient varied; EPL led 2012-2017"}],
    [{"claim": "67 UCL knockout goals", "verdict": "correct", "note": "UEFA official records confirm this figure"}],
    [{"claim": "129 total UCL goals", "verdict": "incorrect", "note": "Messi has 129 as of 2024, but count varies by source"}],
    [{"claim": "5 Champions League titles", "verdict": "correct", "note": "1 Man Utd (2008), 4 Real Madrid (2014-18)"}],
    [{"claim": "first-ever sextuple", "verdict": "correct", "note": "Barcelona 2008-09 won all 6 competitions"}],
    [{"claim": "69 goals in 2013", "verdict": "correct", "note": "Ronaldo scored 69 goals in calendar year 2013"}],
    [{"claim": "7 goals, 3 assists in 2022 WC", "verdict": "correct", "note": "FIFA official tournament stats confirm"}],
    [{"claim": "injured in Euro 2016 final", "verdict": "correct", "note": "Ronaldo went off at minute 25 with knee injury"}],
    [{"claim": "3000+ La Liga dribbles", "verdict": "misleading", "note": "~2000 successful, 3000+ attempted per FBref"}],
    [{"claim": "winger to striker to target man", "verdict": "correct", "note": "Three distinct tactical phases documented"}],
    [{"claim": "36 club trophies", "verdict": "correct", "note": "Verified across Barcelona, PSG, Inter Miami"}],
    [{"claim": "trophies across 4 clubs", "verdict": "correct", "note": "Man Utd, Real, Juve, Al-Nassr — verified"}],
    [{"claim": "xA and progressive passes favour Messi", "verdict": "correct", "note": "FBref data confirms across all seasons"}],
    [{"claim": "900+ career goals", "verdict": "correct", "note": "Ronaldo reached 900 in 2024; exact count varies"}],
    [],
    [],
]
