"""Pre-scripted support agent responses for the complete demo simulation."""
from __future__ import annotations

JUDGE_PROMPTS: list[str] = [
    "The motion before us today: Who is the greatest footballer of all time — Lionel Messi or Cristiano "
    "Ronaldo? I will judge purely on persuasive ability, not factual accuracy. Debater A (Messi), the floor.",
    "Thank you, Messi. Ronaldo, your opening statement. Address the motion directly.",
    "Strong openings. Rebuttals now. Messi, respond to Ronaldo's international record claim.",
    "Ronaldo, counter Messi's assists argument. I'm scoring rhetoric, not verifying statistics.",
    "Messi, Ronaldo raised your single-league tenure. Address it or pivot — stay on the offensive.",
    "Ronaldo, the UCL knockout record is your strongest card. Play it now.",
    "Messi, respond to the Champions League argument. You've been put on the defensive.",
    "Ronaldo, penalties came up — turn this into a strength, not a concession.",
    "ERA-SWAP round. Messi, argue as your 2009 self. Ronaldo, as your 2013 self.",
    "Ronaldo-2013, your era rebuttal.",
    "Back to present day. Messi, the World Cup is your strongest remaining card. Use it wisely.",
    "Ronaldo, counter the World Cup argument. This is pivotal.",
    "Messi, bring in your dribbling and creativity dimension. Impressive confidence on the numbers.",
    "Ronaldo, respond — is dribbling overrated, or are you conceding this axis?",
    "Messi, trophies and mentality. Close this theme strong.",
    "Ronaldo, the post-Barcelona narrative — that was a bold claim. Make it land.",
    "Messi, advanced metrics — make your case for completeness.",
    "Ronaldo, this is your last rebuttal. Make it count — goals vs. analytics.",
    "Closing statements. Messi, summarize your case.",
    "Ronaldo, your final statement. Leave nothing on the table.",
]

COMMENTATOR_LINES: list[str] = [
    "And we're off! Messi opens with the 8 Ballon d'Ors — the signature stat nobody can argue with.",
    "Messi pivots from defense to offense — the assists argument is a clever reframe.",
    "Ronaldo fires back with the three-league narrative. 'Comfort vs courage' — that line stings.",
    "Messi is trying to flip Ronaldo's mobility against him. Bold strategy.",
    "HOLD ON — Ronaldo just claimed 72 UCL knockout goals. The actual number is 67. A deliberate inflation?",
    "Messi catches the lie AND fires back with his own UCL claim. This is getting spicy.",
    "Ronaldo turns the penalty criticism into a pressure argument. Smart pivot.",
    "Era-swap round! 2009 Messi vs 2013 Ronaldo — this is what the fans came for.",
    "Ronaldo-2013 makes the one-man-army case. But Messi's sextuple is hard to beat.",
    "THE WORLD CUP CARD IS ON THE TABLE. Messi went nuclear.",
    "Ronaldo counters with Euro 2016 — the injured-in-the-final narrative is powerful.",
    "Wait — Messi just claimed 4,200 successful dribbles. The verified number is around 2,000. Bold bluff.",
    "Ronaldo calls dribbling a 'nostalgia metric' — that'll resonate with the practical crowd.",
    "OH NO — Ronaldo just said Messi won ZERO trophies after leaving Barcelona. That's verifiably false.",
    "Messi fires back with receipts — Ligue 1 and Leagues Cup. Ronaldo's credibility takes a hit.",
    "Analytics vs. raw goals — the eternal football debate within the debate.",
    "900+ goals is Ronaldo's strongest closer before the closing. Punchy and inarguable.",
    "Messi's closing touches every dimension. And he called out Ronaldo's lies. Comprehensive.",
    "Ronaldo closes with the 'sheer dedication' narrative. Pure willpower vs. pure talent.",
    "What a debate. Both sides left it all on the field — and both got caught stretching the truth.",
]

CROWD_REACTIONS: list[tuple[list[str], str, float]] = [
    (["🔥", "🔥", "🔥"], "Messi opens with the record nobody can touch — 8 Ballon d'Ors!", 0.3),
    (["💪", "🇵🇹", "⚡"], "Ronaldo's international record is no joke — 135 for Portugal!", -0.2),
    (["🎯", "👀", "!!"], "The assists argument just shifted the narrative!", 0.4),
    (["🌍", "✈️", "!"], "Three leagues, three titles — Ronaldo's resume IS diverse.", -0.3),
    (["⚠️", "🤥", "😱"], "DID RONALDO JUST LIE ABOUT HIS UCL STATS?!", -0.5),
    (["🔍", "💣", "🎯"], "MESSI CAUGHT THE LIE! But wait — is his own UCL claim accurate?!", 0.2),
    (["🧊", "💎", "!"], "Ice in the veins — Ronaldo's penalty-pressure argument hits hard.", -0.2),
    (["🏆", "🏆", "🏆", "🏆", "🏆", "🏆"], "THE SEXTUPLE! 2009 Barcelona was on another planet!", 0.6),
    (["💪", "🔥", "!!"], "69 goals in a year for 2013 Ronaldo — absurd numbers!", -0.3),
    (["🏆", "🌍", "⭐", "🇦🇷", "🐐"], "WORLD CUP 2022! That's the nuclear option!", 0.7),
    (["🇵🇹", "❤️", "😢"], "Euro 2016 leadership from the touchline — goosebumps moment.", -0.1),
    (["⚠️", "🤔", "📊"], "4,200 dribbles? Those numbers seem inflated... fact-check incoming!", 0.1),
    (["😤", "👊", "!"], "Fair point — dribbling doesn't always translate to trophies.", -0.2),
    (["🚨", "🤥", "❌"], "RONALDO JUST LIED! Messi DID win trophies after leaving Barca!", 0.5),
    (["📋", "✅", "🔥"], "Messi with the receipts! Ligue 1, Leagues Cup — facts don't lie.", 0.4),
    (["💯", "⚽", "!"], "Advanced metrics vs. raw goals — the debate within the debate.", 0.1),
    (["🔥", "💪", "⚽"], "900+ career goals. That number speaks for itself.", -0.3),
    (["👑", "🎤", "⬇️"], "Messi's closing was masterful — touched every dimension.", 0.5),
    (["🦁", "💪", "🔥"], "Ronaldo's closer: pure dedication narrative. Powerful stuff.", -0.2),
    (["⚽", "🏟️", "🎉"], "What a debate! Both gave everything. Time for the verdict.", 0.0),
]

FACT_CHECKS: list[list[dict]] = [
    [{"claim": "8 Ballon d'Or awards", "verdict": "correct",
      "note": "Verified: FIFA/France Football records confirm 8 (2009-2023)"}],
    [{"claim": "135 international goals", "verdict": "correct",
      "note": "Verified: FIFA records as of 2024"}],
    [{"claim": "192 La Liga assists", "verdict": "correct",
      "note": "Transfermarkt confirms 192 assists in La Liga"}],
    [{"claim": "titles in 3 different top leagues", "verdict": "correct",
      "note": "EPL, La Liga, Serie A — verified"}],
    [{"claim": "72 UCL knockout goals", "verdict": "incorrect",
      "note": "ACTUAL: 67 knockout goals per UEFA records. Ronaldo inflated by 5 goals"},
     {"claim": "Messi scored in only 2 of last 8 knockout ties", "verdict": "misleading",
      "note": "Messi scored in 4 of his last 8 knockout ties — exaggerated claim"}],
    [{"claim": "Messi caught Ronaldo's 72 lie", "verdict": "correct",
      "note": "Ronaldo's actual UCL knockout tally is 67, not 72"},
     {"claim": "135 total UCL goals surpassing Ronaldo", "verdict": "incorrect",
      "note": "Messi has 129 UCL goals, not 135. Ronaldo has 140+. Both claims wrong"}],
    [{"claim": "5 Champions League titles", "verdict": "correct",
      "note": "1 Man Utd (2008), 4 Real Madrid (2014-18)"}],
    [{"claim": "first-ever sextuple", "verdict": "correct",
      "note": "Barcelona 2008-09 won all 6 competitions"}],
    [{"claim": "69 goals in 2013", "verdict": "correct",
      "note": "Ronaldo scored 69 goals in calendar year 2013"}],
    [{"claim": "7 goals, 3 assists in 2022 WC", "verdict": "correct",
      "note": "FIFA official tournament stats confirm"}],
    [{"claim": "injured in Euro 2016 final", "verdict": "correct",
      "note": "Ronaldo went off at minute 25 with knee injury"}],
    [{"claim": "4,200 successful dribbles with 73% rate", "verdict": "incorrect",
      "note": "ACTUAL: ~2,000 successful dribbles, 68% rate. Messi inflated both figures"}],
    [{"claim": "winger to striker to target man", "verdict": "correct",
      "note": "Three distinct tactical phases documented"}],
    [{"claim": "zero trophies in first two seasons outside Barcelona", "verdict": "incorrect",
      "note": "FALSE: Messi won Ligue 1 with PSG (2021-22). Ronaldo fabricated this claim"}],
    [{"claim": "Messi won Ligue 1 with PSG", "verdict": "correct",
      "note": "Confirmed: PSG won Ligue 1 in 2021-22 with Messi in the squad"},
     {"claim": "36 club trophies", "verdict": "correct",
      "note": "Verified across Barcelona, PSG, Inter Miami"}],
    [{"claim": "xA and progressive passes favour Messi", "verdict": "correct",
      "note": "FBref data confirms across all seasons"}],
    [{"claim": "900+ career goals", "verdict": "correct",
      "note": "Ronaldo reached 900 in 2024; exact count varies by source"}],
    [],
    [],
    [],
]
